name: Build and Push Image CI

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image tag'
        required: true
        type: string

jobs:

  build:
    name: Build and Push
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build --tag frontend .

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0

    - name: Set up registry connection
      run: gcloud auth configure-docker --quiet

    - name: Push the docker image
      run: |
        docker tag frontend gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/frontend:${{ inputs.imageTag }}
        docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/frontend:${{ inputs.imageTag }}